services:
  pdnsdb:
    image: mariadb:10.6
    container_name: pdnsdb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-powerdns}
      - MYSQL_USER=${MYSQL_USER:-pdns}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pdnspassword}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  pdnsapp:
    image: processton/power-dns:latest
    container_name: pdnsapp
    depends_on:
      - pdnsdb
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8081:${PDNS_WEBSERVER_PORT:-8081}"
    volumes:
      - ./conf:/etc/powerdns
    environment:
      - MYSQL_HOST=pdnsdb
      - MYSQL_DATABASE=${MYSQL_DATABASE:-powerdns}
      - MYSQL_USER=${MYSQL_USER:-pdns}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pdnspassword}
      - PDNS_API_KEY=${PDNS_API_KEY:-changeme}
      - PDNS_WEBSERVER_PORT=${PDNS_WEBSERVER_PORT:-8081}
      - PDNS_WEBSERVER_ADDRESS=${PDNS_WEBSERVER_ADDRESS:-0.0.0.0}
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM:-0.0.0.0/0}
    restart: unless-stopped

  pdnsadmin:
    image: processton/pdns-admin:latest
    container_name: pdnsadmin
    depends_on:
      - pdnsdb
      - pdnsapp
    ports:
      - "80:80"
    environment:
      - PDNS_API_URL=http://pdnsapp:8081
      - PDNS_API_KEY=${PDNS_API_KEY:-changeme}
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - MYSQL_HOST=pdnsdb
      - MYSQL_DATABASE=${MYSQL_DATABASE:-powerdns}
      - MYSQL_USER=${MYSQL_USER:-pdns}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pdnspassword}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@local.domain}
      - ADMIN_FIRSTNAME=${ADMIN_FIRSTNAME:-Admin}
      - ADMIN_LASTNAME=${ADMIN_LASTNAME:-User}
      - OTP_ENABLED=${OTP_ENABLED:-false}
    restart: unless-stopped

volumes:
  mysql_data:
