version: '3.8'
services:
  powerdns:
    build: .
    container_name: powerdns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "80:${PDNS_WEBSERVER_PORT:-8081}"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf:/etc/powerdns
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER_PORT=${PDNS_WEBSERVER_PORT}
      - PDNS_WEBSERVER_ADDRESS=${PDNS_WEBSERVER_ADDRESS}
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}

